run:
  timeout: 5m

linters:
  disable:
    - maligned
    - gochecknoglobals

linters-settings:
  govet:
    check-shadowing: true

enable:
  - govet
  - errcheck
  - staticcheck
  - gosimple
  - unused
